apiVersion: v1
kind: Service
metadata:
  name: {{ include "electric-car.fullname" . }}
  labels:
    {{- include "electric-car.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    {{- include "electric-car.selectorLabels" . | nindent 4 }}
