apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-node-chrome-rep
spec:  
  replicas: 3
  selector:
    app: selenium-node-chrome
  template:
    metadata:
      name: selenium-node-chrome
      labels:
        app: selenium-node-chrome
    spec:
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome
          ports:
            - containerPort: 5900
          env:
           - name:  HUB_HOST
             value: "selenium-srv" 
           - name: HUB_PORT
             value: "4444"
